apps:
- name: "{{ cookiecutter.projectName }}"
  components:
    - name: "{{ cookiecutter.projectName }}"
      host: "github"
      repo: "{{ cookiecutter.repositoryOwner }}/{{ cookiecutter.repositoryName }}"
      path: templates/service-template.yaml